Bug fixes
adhorrig/spodl pull request #10
Opened 2017-02-20 22:29 UTC by AnthonyBloomer

This PR addresses two issues:

1. If we just run ```npm install``` we won't be able to run ```spodl spotify_account_name spotify_playlist_id```. The only way that will work is if we install globally using ```npm install -g```

2. If the user specifies the download directory in the config file, we still create a folder in the current directory with the playlist name so I've removed the function createDirectory. youtube-dl will handle that for us anyway.

2017-02-20 22:57 UTC, adhorrig commented on src/index.js
> -  if (!fs.existsSync(playlistName))
If this is removed what happens if a playlist is downloaded twice to the same directory? There is no check anymroe

2017-02-21 15:22 UTC, AnthonyBloomer commented
If the directory doesn't exist then youtube-dl will create it. If it does exist then youtube-dl will download the playlist into that directory.

2017-02-25 14:10 UTC, adhorrig requested changes
Readme update and creating of the directory looks good. However, I still want to use the config file for the API keys rather than environment variables.

Also try squash the commits again :)

2017-02-25 14:10 UTC, adhorrig commented on package.json
> +		"url": "git+https://github.com/anthonybloomer/spodl.git"
Wrong url

2017-02-25 14:10 UTC, adhorrig commented on package.json
> +		"url": "https://github.com/anthonybloomer/spodl/issues"
Again

2017-02-25 14:10 UTC, adhorrig commented on package.json
> +	"homepage": "https://github.com/anthonybloomer/spodl#readme",
Again

2017-02-25 14:10 UTC, adhorrig commented on config.js
> -module.exports = {
I'd rather handle the API keys this way than through ENV variables

2017-02-25 14:10 UTC, adhorrig commented on src/index.js
> +  const cmd = process.argv[4] === 'video' ? 'youtube-dl -o "' + playlistName + '/%(title)s.%(ext)s"'  :
Looks good 💯

2017-11-15 15:02 UTC, closed without merging