Modernised. Untested.
adhorrig/spodl pull request #5
Opened 2017-02-04 20:15 UTC by simonccarter

Untested! I don't have Spotify api keys. Please test this, especially promises.

Run locally on node version 6.9.1.

Changes include:

Use arrow functions
Use function composition
Use pure functions
Replace var with let/const
Replace initial if/else with just single if
Move what looks like unnecessary youtube initialisation outside of youtube function to global scope.
Replace for loop with forEach
Replace sys with util
Global ternary statement rather than unnecessary local if/else for cmd string init

2017-02-05 20:38 UTC, adhorrig requested changes
Mostly looks great, I noticed two small things though!

2017-02-05 20:38 UTC, adhorrig commented on src/index.js
> +  if(error) console.log('exec error: '+error);
```Error``` is not defined, should be using ```err``` here.

2017-02-05 20:38 UTC, adhorrig commented on src/index.js
> +  else      util.print('stdout: '+stdout);
Could this whitespace be reduced?

2017-02-06 18:41 UTC, simonccarter commented
Pushed an update to include your requested changes. If you want to test this before merge, you can always pull from my fork :)

2017-02-06 18:48 UTC, adhorrig commented on src/index.js
> +  if(er) console.log('exec error: '+error);
Forgot one 'r' :), also the ```error``` in the print statement should also be ```err``` too

2017-02-06 18:49 UTC, adhorrig commented
I tested when reviewing and that was the only issue, I added a comment to the latest commit. After that it should be good to be merged 😃

2017-02-06 22:15 UTC, simonccarter commented
And again. Rebased.

2017-02-06 22:25 UTC, adhorrig approved these changes

2017-02-06 22:25 UTC, merged

2017-02-06 22:26 UTC, adhorrig commented
Perfect 👍 Thanks a bunch!